/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package localnetworkdrive;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.json.*;
import RTP.FTPClientAPI;
import RTP.FTPServerAPI;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kesha
 */
public class HomePage extends javax.swing.JFrame {
public String jsonresp;
public JSONArray json;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file = new javax.swing.JDialog();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        back1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        opt1 = new javax.swing.JButton();
        opt2 = new javax.swing.JButton();
        opt3 = new javax.swing.JButton();
        opt4 = new javax.swing.JButton();
        opt5 = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        file.setMinimumSize(new java.awt.Dimension(715, 470));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 140, 30));

        jList1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jLayeredPane2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 510, 370));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel3.setText("Remote File Transfer");
        jLayeredPane2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 250, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jButton2.setText("Download");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 140, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jButton3.setText("Upload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 140, 30));

        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/localnetworkdrive/back.jpg"))); // NOI18N
        jLayeredPane2.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 430));

        javax.swing.GroupLayout fileLayout = new javax.swing.GroupLayout(file.getContentPane());
        file.getContentPane().setLayout(fileLayout);
        fileLayout.setHorizontalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );
        fileLayout.setVerticalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Local Storage Drive");

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel2.setText("Local Storage Drive");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 240, -1));

        opt1.setBackground(new java.awt.Color(255, 255, 255));
        opt1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        opt1.setForeground(new java.awt.Color(51, 0, 204));
        opt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/localnetworkdrive/play.png"))); // NOI18N
        opt1.setText("Video Streaming");
        opt1.setToolTipText("");
        opt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opt1.setContentAreaFilled(false);
        opt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opt1.setName("op1"); // NOI18N
        opt1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLayeredPane1.add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, 240));

        opt2.setBackground(new java.awt.Color(255, 255, 255));
        opt2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        opt2.setForeground(new java.awt.Color(51, 0, 204));
        opt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/localnetworkdrive/CinemaDisplay-icon.png"))); // NOI18N
        opt2.setText("Screen Mirroring");
        opt2.setToolTipText("");
        opt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opt2.setContentAreaFilled(false);
        opt2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opt2.setName("op1"); // NOI18N
        opt2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLayeredPane1.add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 170, 240));

        opt3.setBackground(new java.awt.Color(255, 255, 255));
        opt3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        opt3.setForeground(new java.awt.Color(51, 0, 204));
        opt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/localnetworkdrive/Button-Help-icon.png"))); // NOI18N
        opt3.setText("Help");
        opt3.setToolTipText("");
        opt3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opt3.setContentAreaFilled(false);
        opt3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opt3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opt3.setName("op1"); // NOI18N
        opt3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLayeredPane1.add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 170, 240));

        opt4.setBackground(new java.awt.Color(255, 255, 255));
        opt4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        opt4.setForeground(new java.awt.Color(51, 0, 204));
        opt4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/localnetworkdrive/Button-Close-icon.png"))); // NOI18N
        opt4.setText("Exit");
        opt4.setToolTipText("");
        opt4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opt4.setContentAreaFilled(false);
        opt4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opt4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opt4.setName("op1"); // NOI18N
        opt4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 170, 240));

        opt5.setBackground(new java.awt.Color(255, 255, 255));
        opt5.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        opt5.setForeground(new java.awt.Color(51, 0, 204));
        opt5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/localnetworkdrive/Hard-Disk-Wifi-icon.png"))); // NOI18N
        opt5.setText("Remote Storage");
        opt5.setToolTipText("");
        opt5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        opt5.setContentAreaFilled(false);
        opt5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opt5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opt5.setName("op1"); // NOI18N
        opt5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        opt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(opt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 240));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/localnetworkdrive/back.jpg"))); // NOI18N
        jLayeredPane1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_opt4ActionPerformed

    private void opt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5ActionPerformed
        // TODO add your handling code here:
        file.setVisible(true);
    }//GEN-LAST:event_opt5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fetchfiles f = new fetchfiles();
        jsonresp = f.getHTML("http://192.168.0.17:3000/files/get/");
        json = new JSONArray(jsonresp);
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<json.length();i++)
        {
            model.addElement(json.getJSONObject(i).getString("absolutepath"));
        }
        ImageIcon jv = new ImageIcon(HomePage.class.getResource("java.png"));
        ImageIcon py = new ImageIcon(HomePage.class.getResource("python.png"));
        ImageIcon mp = new ImageIcon(HomePage.class.getResource("mp4.png"));
        JSONObject rec;
        //model.add(0,jv);
        //model.add(1,py);
        //model.add(2,mp);
        jList1.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String file = (String)jList1.getSelectedValue();
        int i = 0;
        for(i=0;i<jsonresp.length()-1;i++)
        {
            if(file.equals(json.getJSONObject(i).getString("absolutepath")))
                break;
        }
        String ip = json.getJSONObject(i).getString("ip");
        String srcip = json.getJSONObject(i).getString("originip");
        String filename = json.getJSONObject(i).getString("absolutepath");
        //JOptionPane.showMessageDialog(null,"IP"+ip+"\noriginIP:"+srcip+"\npath:"+filename);
        //API CALL
        FTPClientAPI fc = new FTPClientAPI(ip);
    try {
        fc.ReceiveFile(filename);
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    finally
            {
                System.out.println("Done");
            }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FTPClientAPI fc = new FTPClientAPI("192.168.0.9");
        
        try
        {
            fc.SendFile("C:\\Users\\kesha\\Desktop\\t.java");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel back1;
    private javax.swing.JDialog file;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton opt1;
    private javax.swing.JButton opt2;
    private javax.swing.JButton opt3;
    private javax.swing.JButton opt4;
    private javax.swing.JButton opt5;
    // End of variables declaration//GEN-END:variables
}
